name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

env:
  VM_IP: ${{ secrets.VM_IP }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python-docker-demo5:latest

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.VM_IP }} \
          "docker stop python-app || true && \
           docker rm python-app || true && \
           docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/python-docker-demo5:latest && \
           docker run -d -p 5000:5000 --name python-app ${{ secrets.DOCKER_HUB_USERNAME }}/python-docker-demo5:latest"